name: Shell Commands # Workflow'un ismi, bu isim github actions sekmesinde gorunur, isim vermezsek dosyanin adi isim olur

on: [push] # event'ler on ile tanimlanir, ister bir event istersek de array ov event olarak tanimlanabilir

jobs: # bu bir obje olabilir, ve objenin her key'i job ismi olur
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: eccho "Hello world Ali Balbars"
      - name: multiline script
        run: |
          node -v
          npm -v

          

# job isminde sadece dash ya da underscore olabilir; space olamaz
# her job bir obje olarak tanimlanir
# jobs icinde objeler olan bir objedir
# her jobin hangi operating sistemde calismasi gerektigini belirtmemiz gerekir
# steps, obje arrayidir ve her obje bir stepi temsil eder
# step'lere name verilebilir fakat required degildir
# bir step ya bir action calistirir ya da bir shell command calistirir (shell command calistirmak icin run keywordu kullanilir)
